labels = [
    "Coupe",
    "Motorcyclist",
    "Yield Sign",
    "SUV",
    "Wheelchair User",
    "Hatchback",
    "Pedestrian Detour Sign",
    "Construction Worker",
    "Information Sign",
    "Truck Cab",
    "Speed Limit Sign",
    "Bus",
    "Box Truck",
    "Cyclist",
    "Adult Pedestrian",
    "Bus Sign",
    "Vehicular Trailer",
    "School Bus",
    "Construction Barrier",
    "Police Car",
    "Police / Emergency Worker",
    "Street Sign",
    "Warning Sign",
    "Stop Sign",
    "Van",
    "Child Pedestrian",
    "Pickup Truck",
    "Truck",
    "Construction Vehicle",
    "Motorbike",
    "Articulated Bus",
    "Message Board Trailer",
    "Radar Speed Sign",
    "Parking Sign",
    "Sedan",
    "Traffic Light Trailer",
    "Directional Arrowboard",
]

colors = [
    "beige",
    "green",
    "yellow",
    "black",
    "white",
    "silver",
    "brown",
    "gray",
    "purple",
    "blue",
    "orange",
    "gold",
    "red",
]
